- hosts: PE
  gather_facts: False
  tasks:
  - name: Configurando VRF
    iosxr_config:
      lines:
      - vrf {{vrf}}
  - name: Habilitando Address-Family en VRF
    iosxr_config:
      lines:
      - address-family ipv4 unicast
      parents: vrf {{vrf}}
  - name: Configurando Route-targets en VRF
    iosxr_config:
      lines:
      - import route-target {{route_target}}
      - export route-target {{route_target}}
      parents:
      - vrf {{vrf}}
      - address-family ipv4 unicast

- hosts: PE
  gather_facts: False
  tasks:
  - name: Habilitando VRF en BGP
    iosxr_config:
      lines:
      -  vrf {{vrf}}
      parents:
      - router bgp {{bgp_as}}
  - name: Habilitando RD & Address-Family
    iosxr_config:
      lines:
      - rd {{rd}}
      - address-family ipv4 unicast
      parents:
      - router bgp {{bgp_as}}
      - vrf {{vrf}}
  - name: Redistribuyendo rutas
    iosxr_config:
      lines:
      - redistribute connected
      parents:
      - router bgp {{bgp_as}}
      - vrf {{vrf}}
      - address-family ipv4 unicast
  - name: Habilitando interfaz y direccionamiento para L3VPN
    iosxr_config:
      lines:
      - no shutdown
      - ipv4 address {{ip_pe}}
      - vrf {{vrf}}
      parents: interface {{interface_pe}}
